services:
  - type: web
    name: steam-wishlist-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: STEAM_COOKIE
        sync: false   # lo pondrás manualmente en el dashboard